# Generated by Django 3.1.1 on 2021-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20210410_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='standard',
            field=models.CharField(choices=[('1', '1-star'), ('2', '2-star'), ('3', '3-star'), ('4', '4-star'), ('5', '5-star')], max_length=50, null=True),
        ),
    ]
