# Generated by Django 3.1.1 on 2021-04-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20210410_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adult_count', models.IntegerField()),
                ('children_count', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
