# Generated by Django 3.1.1 on 2021-04-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20210410_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.travel'),
        ),
    ]
