# Generated by Django 3.1.1 on 2021-04-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20210410_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='travel.hotel'),
        ),
    ]
