# Generated by Django 3.1.1 on 2021-04-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_travel_promoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='type',
            field=models.CharField(choices=[('1', 'BB'), ('2', 'HB'), ('2', 'FB'), ('3', 'AI')], max_length=50, null=True),
        ),
    ]
