# Generated by Django 3.1.1 on 2021-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20210410_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
