# Generated by Django 3.1.1 on 2021-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20210411_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
