# Generated by Django 3.1.1 on 2021-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20210411_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='type',
            field=models.CharField(choices=[('1', 'BB'), ('2', 'HB'), ('3', 'FB'), ('4', 'AI')], max_length=50, null=True),
        ),
    ]
