# Generated by Django 3.1.1 on 2021-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20210411_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(null=True, upload_to='travel/'),
        ),
    ]
