# Generated by Django 3.1.1 on 2021-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_travel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/travel/'),
        ),
    ]
