# Generated by Django 3.1.1 on 2021-04-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_auto_20210412_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
